services:
  postgres:
    ports:
      - '5433:5432'
    networks:
      - default
      - pgadmin

  keycloak:
    ports:
      - '8090:8080'

  webapp:
    volumes:
      - m2-cache:/root/.m2
    develop:
      watch:
        - action: sync
          path: ./src/main/java
          target: /app/src/main/java
    ports:
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  m2-cache:

networks:
  pgadmin:
    name: composes_default
    external: true
