services:
  postgres:
    ports:
      - '5433:5432'
    networks:
      - default
      - pgadmin

  keycloak:
    ports:
      - '8080:8080'

  redis:
    ports:
      - '6379:6379'

  minio:
    ports:
      - '9001:9001'

  webapp:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - m2-cache:/root/.m2
    develop:
      watch:
        - action: sync
          path: ./backend/src/main/java
          target: /app/src/main/java
    ports:
      - '8000:8000'
      - '8090:8080'
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
    ports:
      - '5173:5173'

volumes:
  m2-cache:

networks:
  pgadmin:
    name: composes_default
    external: true
