spring:
  application:
    name: price_aggregator
    version: 1.0

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${WEBAPP_DBNAME}
    username: ${WEBAPP_DB_USERNAME}
    password: ${WEBAPP_DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    mapping-resources:
      - query/category-tree.xml
      - query/child-categories-names.xml
      - query/daily-price-dynamics.xml
      - query/monthly-price-dynamics.xml
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        cache:
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_query_cache: true
          use_second_level_cache: true
          redisson:
            productsSummaryCache:
              expiration:
                max_entities: 1000
                time_to_live: 3600000
            categoriesCache:
              expiration:
                max_entities: 1000
                time_to_live: 259200000
            vendorsCache:
              expiration:
                max_entities: 1000
                time_to_live: 259200000
            productsCache:
              expiration:
                max_entities: 1000
                time_to_live: 3600000
            reviewsCache:
              expiration:
                max_entities: 100
                time_to_live: 259200000
            query:
              eviction:
                max_entries: 500
                expiration:
                  time_to_live: 14400000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KC_HOST}:8080/realms/${KC_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jackson:
    default-property-inclusion: non_empty

keycloak:
  server-url: http://${KC_HOST}:8080
  realm: ${KC_REALM}
  username: ${KC_ADMIN_USERNAME}
  password: ${KC_ADMIN_PASSWORD}
  client-database-id: ${KC_CLIENT_DATABASE_ID}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

swagger:
  application:
    title: Price Aggregator Project
    description: An application that helps you choose a store with the best prices
