spring:
#  jpa:
#    properties:
#      hibernate:
#        generate_statistics: true

logging:
  level:
    org.hibernate.stat: DEBUG
    org.springframework.security: DEBUG

server:
  ssl:
    enabled: false
