spring:
  application:
    name: price_aggregator
    version: 1.0

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${WEBAPP_DBNAME}
    username: ${WEBAPP_DB_USERNAME}
    password: ${WEBAPP_DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KC_HOST}:8080/realms/${KC_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  server-url: http://${KC_HOST}:8080
  realm: ${KC_REALM}
  username: ${KC_ADMIN_USERNAME}
  password: ${KC_ADMIN_PASSWORD}
  client-database-id: ${KC_CLIENT_DATABASE_ID}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}

swagger:
  application:
    title: Price Aggregator Project
    description: An application that helps you choose a store with the best prices
