spring:
  jpa:
    properties:
      cache:
        redisson:
          productsSummaryCache:
            expiration:
              max_entities: 1000
              time_to_live: 3600000
          categoriesCache:
            expiration:
              max_entities: 1000
              time_to_live: 259200000
          vendorsCache:
            expiration:
              max_entities: 1000
              time_to_live: 259200000
          productsCache:
            expiration:
              max_entities: 1000
              time_to_live: 3600000
          reviewsCache:
            expiration:
              max_entities: 100
              time_to_live: 259200000
          query:
            eviction:
              max_entries: 500
              expiration:
                time_to_live: 14400000
