spring:
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true

logging:
  level:
    org.hibernate.stat: DEBUG
    org.springframework.security: DEBUG
