name: Build and publish container images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build and push containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: backend_meta
        name: Generate backend image metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/aggregator-backend
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - id: frontend_meta
        name: Generate frontend image metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/aggregator-frontend
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push backend image
        uses: docker/build-push-action@v6.17.0
        with:
          context: "{{defaultContext}}:backend"
          tags: ${{ steps.backend_meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true

      - name: Cleanup untagged backend images
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-type: container
          package-name: aggregator-backend
          delete-only-untagged-versions: true
          min-versions-to-keep: 0

      - name: Build and push frontend image
        uses: docker/build-push-action@v6.17.0
        with:
          context: "{{defaultContext}}:frontend"
          tags: ${{ steps.frontend_meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true

      - name: Cleanup untagged frontend images
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-type: container
          package-name: aggregator-frontend
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
